-- Copyright 2026 Entity Customer Semantic Search in Db2 LUW Project
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- ============================================================================
-- Customer Semantic Search - Sample Data Loading
-- ============================================================================
-- This script loads sample data from CSV files generated by generate_sample_data.py
-- Run: python3 scripts/generate_sample_data.py first to generate the data files
-- ============================================================================

SET SCHEMA CUSTOMER_SEARCH;

-- ============================================================================
-- Load Income Bands
-- ============================================================================
IMPORT FROM data/income_band.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO INCOME_BAND;

-- ============================================================================
-- Load Customer Demographics
-- ============================================================================
IMPORT FROM data/customer_demographics.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO CUSTOMER_DEMOGRAPHICS;

-- ============================================================================
-- Load Household Demographics
-- ============================================================================
IMPORT FROM data/household_demographics.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO HOUSEHOLD_DEMOGRAPHICS;

-- ============================================================================
-- Load Customer Addresses
-- ============================================================================
IMPORT FROM data/customer_address.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO CUSTOMER_ADDRESS;

-- ============================================================================
-- Load Customers
-- ============================================================================
IMPORT FROM data/customer.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO CUSTOMER;

-- ============================================================================
-- Load Stores
-- ============================================================================
IMPORT FROM data/store.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO STORE;

-- ============================================================================
-- Load Items
-- ============================================================================
IMPORT FROM data/item.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO ITEM;

-- ============================================================================
-- Load Date Dimension
-- ============================================================================
IMPORT FROM data/date_dim.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO DATE_DIM;

-- ============================================================================
-- Load Store Sales
-- ============================================================================
IMPORT FROM data/store_sales.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO STORE_SALES;

-- ============================================================================
-- Load Store Returns
-- ============================================================================
IMPORT FROM data/store_returns.csv OF DEL 
MODIFIED BY COLDEL| SKIPCOUNT 1
INSERT INTO STORE_RETURNS;

COMMIT;

-- ============================================================================
-- Verification
-- ============================================================================
SELECT 'Sample data loaded successfully' AS STATUS FROM SYSIBM.SYSDUMMY1;
SELECT 'Customers: ' || CAST(COUNT(*) AS VARCHAR(10)) AS COUNT FROM CUSTOMER;
SELECT 'Items: ' || CAST(COUNT(*) AS VARCHAR(10)) AS COUNT FROM ITEM;
SELECT 'Stores: ' || CAST(COUNT(*) AS VARCHAR(10)) AS COUNT FROM STORE;
SELECT 'Sales Transactions: ' || CAST(COUNT(*) AS VARCHAR(10)) AS COUNT FROM STORE_SALES;
SELECT 'Returns: ' || CAST(COUNT(*) AS VARCHAR(10)) AS COUNT FROM STORE_RETURNS;
SELECT 'Date Records: ' || CAST(COUNT(*) AS VARCHAR(10)) AS COUNT FROM DATE_DIM;

-- Made with Bob
